### ISSUE TITLE
Heroku is not being deployed correctly :(

### ISSUE THREAD

**Issue by douglasabrown** [moovel/teamchatviz#65]
This looks simply amazing.  My dreams have been answered.  WOW is all i can say....  then I tried to deploy it and it hangs :( 

I did nothing more than try to deploy it.  

It tells me: Build succeeded

but logs tell me: 

2018-10-17T21:34:40.621928+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=igel.herokuapp.com request_id=cb33f78c-2986-48f3-a721-3d411f6e30af fwd="95.91.240.231" dyno= connect= service= status=503 bytes= protocol=https
2018-10-17T21:34:40.845305+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=igel.herokuapp.com request_id=098f89a4-ff40-4b91-a763-e519d7e51b74 fwd="95.91.240.231" dyno= connect= service= status=503 bytes= protocol=https

PLEASE HELP!  I so want this app... WOW is all i can say and left with pure sadness :( 

Thanks in advance!

**Comment by douglasabrown** [comment]
I started over and this time i receive the following error.  Another member of my team receives the same error. 

`2018-10-18T10:33:23.365529+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-10-18T10:33:23.365529+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-10-18T10:33:23.454448+00:00 heroku[web.1]: Process exited with status 137
2018-10-18T10:33:23.468543+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by Daniel-at-IGEL** [comment]
Hi,

I used the documentation and followed the instruction video to deploy teamchatviz to Heroku. That's the result:

2018-10-18T14:27:58.540080+00:00 heroku[web.1]: State changed from crashed to starting
2018-10-18T14:28:05.602113+00:00 heroku[web.1]: Starting process with command `npm start`
2018-10-18T14:28:07.656374+00:00 app[web.1]: 
2018-10-18T14:28:07.656391+00:00 app[web.1]: > teamchatviz@0.1.0 start /app
2018-10-18T14:28:07.656393+00:00 app[web.1]: > nodemon --ignore node_modules --ignore client index.js
2018-10-18T14:28:07.656394+00:00 app[web.1]: 
2018-10-18T14:28:08.268126+00:00 app[web.1]: [nodemon] 1.11.0
2018-10-18T14:28:08.269424+00:00 app[web.1]: [nodemon] to restart at any time, enter `rs`
2018-10-18T14:28:08.269831+00:00 app[web.1]: [nodemon] watching: *.*
2018-10-18T14:28:08.270334+00:00 app[web.1]: [nodemon] starting `node index.js`
2018-10-18T14:28:08.435387+00:00 app[web.1]: { [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
2018-10-18T14:28:10.749229+00:00 app[web.1]: /app/node_modules/koa/node_modules/debug/src/node.js:132
2018-10-18T14:28:10.749236+00:00 app[web.1]: let val = process.env[key];
2018-10-18T14:28:10.749238+00:00 app[web.1]: ^^^
2018-10-18T14:28:10.749239+00:00 app[web.1]: 
2018-10-18T14:28:10.749241+00:00 app[web.1]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2018-10-18T14:28:10.749242+00:00 app[web.1]: at exports.runInThisContext (vm.js:53:16)
2018-10-18T14:28:10.749244+00:00 app[web.1]: at Module._compile (module.js:373:25)
2018-10-18T14:28:10.749245+00:00 app[web.1]: at Module._extensions..js (module.js:416:10)
2018-10-18T14:28:10.749247+00:00 app[web.1]: at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)
2018-10-18T14:28:10.749248+00:00 app[web.1]: at Module.load (module.js:343:32)
2018-10-18T14:28:10.749249+00:00 app[web.1]: at Function.Module._load (module.js:300:12)
2018-10-18T14:28:10.749251+00:00 app[web.1]: at Module.require (module.js:353:17)
2018-10-18T14:28:10.749252+00:00 app[web.1]: at require (internal/module.js:12:17)
2018-10-18T14:28:10.749254+00:00 app[web.1]: at Object.<anonymous> (/app/node_modules/koa/node_modules/debug/src/index.js:9:19)
2018-10-18T14:28:10.749255+00:00 app[web.1]: at Module._compile (module.js:409:26)
2018-10-18T14:28:10.759114+00:00 app[web.1]: [nodemon] app crashed - waiting for file changes before starting...
2018-10-18T14:29:05.831870+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-10-18T14:29:05.831870+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-10-18T14:29:05.959845+00:00 heroku[web.1]: Process exited with status 137
2018-10-18T14:29:05.969669+00:00 heroku[web.1]: State changed from starting to crashed

Can someone help me? Thank you in advance.
